import { IStorage } from "./IStorage"
import { S3 } from "aws-sdk"
import createError from "fastify-error"
import { ERR_INTERNAL_SERVER } from "../util/errors"
import { basenameOf } from "../util/regexp"

export class S3Storage implements IStorage {
  constructor(
    private readonly s3 = new S3({ region: process.env.AWS_REGION }),
  ) {}

  async save(
    type: "file" | "audio",
    filename: string,
    content: Buffer,
  ): Promise<{ fileUrl: string; thumbnailUrl: string }> {
    const key = `${type}/${filename}`
    const param: S3.Types.PutObjectRequest = {
      Bucket: process.env.AWS_BUCKET_NAME ?? "",
      Key: key,
      Body: content,
      ACL: "public-read",
    }

    let result: S3.ManagedUpload.SendData
    try {
      result = await this.s3.upload(param).promise()
    } catch (e) {
      const err = createError(
        ERR_INTERNAL_SERVER,
        "Failed to upload file.",
        500,
        e,
      )
      throw new err()
    }

    const fileUrl = result.Location
    const basename = basenameOf(filename)
    // This is a url of thumbnail automatically generated by lambda function.
    const thumbnailUrl = `https://${process.env.AWS_BUCKET_NAME}.s3.${process.env.AWS_REGION}.amazonaws.com/thumbnail/${basename}.jpg`

    return { fileUrl, thumbnailUrl }
  }
}
