version: "3.8"
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB:  $DB_NAME
      TZ: Asia/Tokyo
    ports:
      - "15432:5432"
  app:
    build:
      context: ../../
      dockerfile: packages/server/Dockerfile
    image: f-2108-app
    command: yarn dev:server
    environment:
      PORT: $APP_PORT
      DB_HOST: db
    volumes:
      - .:/app/packages/server
    ports:
      - "7000:7000"
    depends_on:
      - db
#  web:
#    build:
#      context: nginx
#    image: f-2108-nginx
#    environment:
#      APP_HOST: app
#      APP_PORT: $APP_PORT
#    volumes:
#      - ./nginx/template:/etc/nginx/templates
#      - ./logs/nginx:/var/log/nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - app
