export const ERR_BAD_URL = "FST_ERR_BAD_URL"
export const ERR_INVALID_PAYLOAD = "FST_ERR_INVALID_PAYLOAD"
export const ERR_TYPE_ASSERT = "FST_ERR_TYPE_ASSERT"
export const ERR_INTERNAL_SERVER = "FST_ERR_INTERNAL_SERVER"
