name: gen-doc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gen-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
      - name: Install packages
        run: yarn
      - name: Generate doc
        run: yarn doc-gen
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto generate doc
          ref: ${{ github.head_ref }}
