name: gen-doc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gen-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
      - name: Install packages
        run: yarn
      - name: Generate doc
        run: yarn doc-gen
      - name: push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "generate doc"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
